### PR TITLE
Implements terminal messages & block explorer links and stores full transaction results or errors

### PR DESCRIPTION
**Pull request by pcaversaccio**
### Final Results

**Success Testnets:**
image

**Error Testnets:**
image

**Success Local:**
image

**Error Local:**
image

### CODE REVIEW

**Comment by defido** [comment]
I like the error additions. I was going to open a discussion on those as they were very long. It might be good to return the ERROR meaning, such as TRANSACTION_FAILED. 

I can write a subtask for the most common one, SALT, deploying the same SALT will always return an error, especially from BSC.

**Comment by defido** [comment]
I have started working on some UX parts, underline for links etc. I'll work around your PR's. I have a general idea how you want to structure things now. 

Screen Shot 2022-03-28 at 1 14 06 pm

**Comment by pcaversaccio** [comment]
Yes, I will add the error meaning & a hint that many errors are due to either low `gasLimit` & already existing contract with the same salt. The error handling is not so trivial since you have to use an opcode view to understand what exactly went wrong (eg using Tenderly). Therefore, a hint is enough IMHO. I personally don't like underlinings - when you hover over it there will be an underline in eg if you use vs code. I will restructure the content a little bit and then we're ready to go.

**Comment by defido** [comment]
Just to note. If the first chain fails. The process will continue. I’d say
exiting the deployment to allow the user to debug would be a better option.

**Comment by pcaversaccio** [comment]
> Just to note. If the first chain fails. The process will continue. I’d say exiting the deployment to allow the user to debug would be a better option.

Well, if it fails for one chain it fails also for the other chains. So it's good to inform the user about the consistency that all other chains also have failed as expected.

**Comment by defido** [comment]
> Well, if it fails for one chain it fails also for the other chains. So it's good to inform the user about the consistency that all other chains also have failed as expected.

You mean let it run even if it fails the first deployment?

**Comment by defido** [comment]
This is the issue, now you have deployed a contract, 2 failed, 1 didn't and you've got to manually upload the others to match them or work out why. 

Screen Shot 2022-03-28 at 8 14 59 pm
FAILED: SALT was used before, continued anyway.
https://testnet.bscscan.com/tx/0xeb7d1e0835f4fe44c95d3230096aad45e14b68a85c593b701731780ca28f6cfe
DEPLOYED: 
https://testnet.ftmscan.com/tx/0xf0265336ae2aad48d02b11db5323b02ff0034d1349a14a7cac9a8c95eb01247b

Contract address same on both, but one failed. Need to redeploy again. This is the pre-checks that save these issues. 

There's 0 going back once something fails in production.

**Comment by pcaversaccio** [comment]
> You mean let it run even if it fails the first deployment?

Sorry, this was a misunderstanding here: I was referring to the contract address computation. In this case, due to the equivalence of the opcodes on all evm chains (and assuming the exact same helper contract deployed on all chains; which is the case for now) 1 failure implies a failure for all selected networks automatically.

so the question is whether I should implement an exit or not after a failed deployment. I'm a little bit hesitant since it's possible to have still successful deployments on the other chains and then you know it's not a general problem but specific to a chain. And there errors could be even different for each failed chain but since we save the debug files for each chain the user can fix all errors simultaneously while otherwise it's kind of stepping through always new deployments.

**Comment by defido** [comment]
That's where I think the env test of a predetermined address the user wants to test against, and just a simple ping to each chain before hand solves som,e but not all of the issues of deploying an address with mistakes. The user could for example, write some code in their contract that randomises the bytecode, and on their second deployment to the next chain, that was NOT part of the 'deploy all at once', then there will be an upload to the chain, and a return of a different address. 

It will be a common use for a user to change the constructor inputs, or a wallet address on the code base, and not realise, "You just changed the BYTECODE!".

I see this kind of like a preflight check, something that is only there to visually warn, not to remove the simplicity of the deployment. Visual proof that the on chain factory will return an address, which the user can verify. 

Then if the contracts don't match, and the user failed to take any notice, then if the contract address is different in production, it's not xdeployers fault.

**Comment by defido** [comment]
You can see a working example of what I was discussing:

Working on localhost/hardhat and on chain. 

It does a ping to the chain to double check, changing the env will add a string to test on chain.

It will test both a local ENV string or if the chain will return a different address randomly

https://github.com/defido/xdeploytest
Screen Shot 2022-03-28 at 11 01 16 pm
Screen Shot 2022-03-28 at 11 00 29 pm

**Comment by defido** [comment]
OK, I will check, in these pre-checks it's not about throwing an error & stopping the run, the user can CTRL + C to do that, the idea is before any deployment. But there should stop the deployment if the first chain fails deployment.

The above I did as a test is not an error, it's just a visual warning with more control for the 'one by one' deployments and testing. A test can't help on that push to production. But if it's not something that xDeployer should do, then I can drop it and figure out where it might be better suited to run. Because if someone pushes the wrong address to production, I want to show them they had a warning before hand.

**Comment by pcaversaccio** [comment]
I added a further comment in the latest comment on the contract address. So what is `xdeployer` really about: it's about the deployment and not what happens pre-deployment actually. Ofc I do sanity checks as you can see, but I cannot cover the full range of error handling given all the various use cases this plugin is used. I think I've done my best in this PR to reflect your input.

**Review by defido — COMMENTED** [review]
Lol, this is so much cleaner, let me test it today. I think the only addition to have this work fully is with the ENV pull in, otherwise, it won't know the previous contract address, or the 'one by one' deployment addresses. 

But this works for the 'all in one' deployments.

Can you think of a way to add previous contract addresses in here that was cleaner than what I had in the push?

**Comment by pcaversaccio** [comment]
well, I do display currently in the prompt now the following message at the beginning of the deployment:
image

Like that you can easily compare it with what you expected. The only open question is whether I should make a full stop there and ask the user to continue (yes/no).

**Comment by defido** [comment]
> well, I do display currently in the prompt now the following message at the beginning of the deployment: image
> 
> Like that you can easily compare it with what you expected. The only open question is whether I should make a full stop there and ask the user to continue (yes/no). I currently tend to no since this is an additional interruption that breaks the flow. If you deploy normally via hardhat also no break exists.

Will test & see let you know. I don't think a yes/no for this part is worth it, the user can break by cancelling the deploy. But it's good to see a visual message. Although, it doesn't show the previous because that's not saved anywhere. Give me a few hours to test it. :D

**Comment by defido** [comment]
I've had a look at the code, and I've played with it a bit, I think this breaks your wanted design of xDeployer being simple. Instead of warning or checking everything beforehand, it's checking 1 chain, pinging 1 chain, then deploying it, then checking chain 2, then deploying, then checking chain 3, then deploying. Meaning, chain 1-2 could be fine, then chain 3 already had the contract address deployed before, but you didn't find out until you deployed the first two. Which is makes this overly complicated.

I feel the messaging should be beforehand, and only as a message to warn someone:

> Error in plugin xdeployer: The address of the contract you want to deploy already has existing bytecode on bscTestnet.
>               It is very likely that you have deployed this contract before with the same salt parameter value.
>               Please try using a different salt value.

Instead it should run beforehand, and reply:

> WARNING: bscTestnet already has this contract address 0xdB4583C1f84Ae56e22653A6D5D114a7bbc5e9318, 
> WARNING: mumbai does not have the contract address  0xdB4583C1f84Ae56e22653A6D5D114a7bbc5e9318
> WARNING: fantomTestNet does not have the contract address 0xdB4583C1f84Ae56e22653A6D5D114a7bbc5e9318
> Check your SALT & bytecode match before proceeding
> A manual upload to the on chain deployer might be needed (See docs for manual deployments)

I think, because these are very different designs for checking before deployment & during each deployment, I might see if I can make an addon, or something within the starters to check these. 

**Would you prefer these checks beforehand were seperate to xDeployer main file?**

**If xDeployer does make any messaging it would be better if it was progress updates and major fails** (Such as this, as it doesn't change the nature of the deployer)

160404011-711e5c3f-bd1a-4b72-9aab-02b707adc7bd

**These prechecks can be moved to a add-on that I will work on, then as complex as they get they don't change the xDeployer**

160404011-711e5c3f-bd1a-4b72-9aab-02b707adc7bd

A multi chain verification script that works off xDeployer module is also in the works. As verifying multiple chains is currently a pain.

**Comment by defido** [comment]
I've done some testing today, and I think a seperate task for these more complicated checks is better. I can make task module that people can use or not if they want. You can then keep xDeployer light, and tasks can be built around. Now I have a better understanding that xDeployer is just one huge task!

But in terms of the messages on main deployments, updates on progress and failures is always welcome 💯 

What do you think?

**Comment by pcaversaccio** [comment]
So `xdeployer` wants to do 2 things:
- Makes sanity pre-checks of the config arguments (like contract name, salt etc.). If those are ok you should be able to deploy under _normal_ circumstances.
- Deployment-specific checks which need an initialisation of the providers and the helper contract. Those happen on a _one-by-one_ basis since I want to guarantee as many as possible successful deployments! Let's say you iterate over the entire network's array and the last fails due to an existing bytecode you don't have to adjust anything in your config file since your task is already done. I think it's a design choice here but my motto is the following: what is chain-agnostic (in our case the config arguments) should be checked beforehand, what is chain-specific (eg related to on-chain information like the helper contract, the computation of the address etc.) should be checked on a one-by-one basis. 

Yeah, I agree to move those more complicated task checks into a task. You could also think of building your own plugin e.g. `xdeployer-checks`. 

I think the current version is however ready to be released. Any further complains ;-)?

**Comment by defido** [comment]
> So `xdeployer` wants to do 2 things:
> 
> * Makes sanity pre-checks of the config arguments (like contract name, salt etc.). If those are ok you should be able to deploy under _normal_ circumstances.
> * Deployment-specific checks which need an initialisation of the providers and the helper contract. Those happen on a _one-by-one_ basis since I want to guarantee as many as possible successful deployments! Let's say you iterate over the entire network's array and the last fails due to an existing bytecode you don't have to adjust anything in your config file since your task is already done. I think it's a design choice here but my motto is the following: what is chain-agnostic (in our case the config arguments) should be checked beforehand, what is chain-specific (eg related to on-chain information like the helper contract, the computation of the address etc.) should be checked on a one-by-one basis.
> 
> Yeah, I agree to move those more complicated task checks into a task. You could also think of building your own plugin e.g. `xdeployer-checks`.
> 
> I think the current version is however ready to be released. Any further complaints ;-)?

No complaints ;), I'll work off whatever you push. I have a different task working and it can be used along side or with the main xdeployer without breaking anything. :D

**Comment by pcaversaccio** [comment]
LFG

**Pull request merged**
