### PR TITLE
💥 Amend Network Additions

### PR DESCRIPTION
**Pull request by itxtoledo**
#### ✅ PR Checklist

- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed in an [issue](https://github.com/pcaversaccio/xdeployer/issues) or in the [discussions](https://github.com/pcaversaccio/xdeployer/discussions) section.
- [x] I didn't do anything of this.

### 🕓 Changelog

This PR aims to achieve two things:

1. Simplify the process of adding new networks. Now, you just need to add a line to the `networksInfo` object to make it work, whereas before, you had to modify two different arrays.
2. Add typing to the configuration of networks supported by the plugin.

#### 🐶 Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Review by pcaversaccio — COMMENTED** [review]
@itxtoledo thx for this PR. I need to think about your suggested changes since it's essentially a breaking API change for the user in the configuration due to the type change. Also, adding a new network to `xdeployer` is a question of a minute :)

**Comment by itxtoledo** [comment]
> @itxtoledo thx for this PR. I need to think about your suggested changes since it's essentially a breaking API change for the user in the configuration due to the type change. Also, adding a new network to `xdeployer` is currently a question of a minute :)

It not break the API, it adds code completion since now the user will now exactly which networks are available.

**Review by pcaversaccio — APPROVED** [review]
Thanks for this refactor. I slightly adjusted the `getTxHashLink` and `getAddressLink` functions, using ternary operators.

**Comment by itxtoledo** [comment]
Thank you for this package !

**Pull request merged**
